### ISSUE TITLE
Spring 6 Upgrade

### ISSUE THREAD

**Issue by garciaerin** [openo-beta/Open-O#32]
**Update 2024-12-03**

Need to look into struts1 to explore if there is an alternative approach to make it compatible with spring 6.

**Update 2024-11-28**

- Refactored most of the javax imports to jakarta imports using IntelliJ's refactor tool (2225 files were changed)
- Added required jakarta dependencies.
Now, we are encountering issues related to struts version - the current struts version 1.3.11 doesn't support jakarta, we need to figure out a solution to ensure struts is compatible with jakarta. (1.5.0-RC2 is the latest struts 1 version which support jakarta, but there were some package access issue occurred when I changed to this version.)

Upgrading to Spring 6 for out Jakarta Migration

**Update 2024 11 27**

- Upgraded Spring to the latest version, 6.2.0
- Added new dependencies needed for this upgrade.

Dependencies added:
```
<!-- added for the deprecated required class -->
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-context</artifactId>
  <version>6.2.0</version> <!-- Use the appropriate version -->
</dependency>

<!-- added for spring 6.2.0 Javamail DNE error-->
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-context-support</artifactId>
  <version>6.2.0</version>
</dependency>
<dependency>
  <groupId>com.sun.mail</groupId>
  <artifactId>javax.mail</artifactId>
  <version>1.6.2</version>
</dependency>

<!-- Spring Integration -->
<dependency>
  <groupId>org.springframework.integration</groupId>
  <artifactId>spring-integration-core</artifactId>
  <version>6.4.0</version>
</dependency>
<dependency>
  <groupId>org.springframework.integration</groupId>
  <artifactId>spring-integration-file</artifactId>
  <version>6.4.0</version>
</dependency>
<dependency>
  <groupId>org.springframework.integration</groupId>
  <artifactId>spring-integration-sftp</artifactId>
  <version>6.4.0</version>
</dependency>

<!-- added for the TransManagerUtils class -->
<dependency>
  <groupId>commons-net</groupId>
  <artifactId>commons-net</artifactId>
  <version>3.11.1</version> 
</dependency>
```

- We were able to fix the first 69 compilation errors that we got after upgrading the spring dependency versions to 6.2.0 by adding those dependencies above. ^^
- There was just this one error that we cannot resolve; it is relating to a package that was no longer in the latest Spring version.
- The error:
```
[ERROR] /workspace/src/main/java/org/oscarehr/app/OscarCsrfGuardFilter.java:[36,49] package org.springframework.web.multipart.commons does not exist
```

- Our only solution is to replace `import org.springframework.web.multipart.commons.CommonsMultipartResolver;` with `import org.springframework.web.multipart.support.StandardServletMultipartResolver;`

- After the replacement, 83 new errors were introduced.
- We are currently solving them by replacing all `javax.servlet` imports with `jakarta.servlet` instead.
- Currently paused because of the Struts related issue.

### WINTER TERM

**Update 2025 01 09**

- Created a new branch called `spring6-upgrade-new` based off `cleanup-pom-security` which has the Struts 2 update.
- Refactored all the javax imports/references to jakarta.
- Added new dependencies relating to Jakarta:

**Update 2025 01 10**
- Encountered 7 errors referenced in the CsrfGuardLogger.java file.
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[27,31] package org.owasp.csrfguard.log does not exist
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[28,31] package org.owasp.csrfguard.log does not exist
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[45,38] cannot find symbol
  symbol: class JavaLogger
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[48,31] cannot find symbol
  symbol:   class LogLevel
  location: class org.oscarehr.app.CsrfGuardLogger
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[81,21] cannot find symbol
  symbol:   class LogLevel
  location: class org.oscarehr.app.CsrfGuardLogger
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[95,21] cannot find symbol
  symbol:   class LogLevel
  location: class org.oscarehr.app.CsrfGuardLogger
[ERROR] /workspace/src/main/java/org/oscarehr/app/CsrfGuardLogger.java:[105,32] cannot find symbol
  symbol:   class LogLevel
  location: class org.oscarehr.app.CsrfGuardLogger
[INFO] 7 errors
```
- Was able to fix the errors by refactoring the code to make it compatible with the imports:
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
```
- And by adding and updating these dependencies:
```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>${slf4j.version}</version>
  <version>2.1.0-alpha1</version>
</dependency>
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>1.5.16</version>
</dependency>
```
